### ISSUE TITLE
How can i use this module to my project like other module?

### ISSUE THREAD

**Issue by surendrakumarkhatik** [ArnaudRinquin/local_modules_poc#3]
Hii @ArnaudRinquin 
I want to create my own module which is used for User curd operation with database connectivity. Now i want to use this module to my other project. How i can do this?
Please help
Thanks in advance @ArnaudRinquin  :)

**Comment by ArnaudRinquin** [comment]
I don't understand your question and won't be able to help with some little details.

I think [stackoverflow](stackoverflow.com) would be a better place for such a question.
